config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dCache/dcache:
      branch: master
      repo: https://github.com/dCache/dcache
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dCache/dcache git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-magnolia-wrasse.sh
        container: qc.acc_thirsty-peach-gar
  QC.Doc:
    repos:
      github.com/dCache/dcache find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-saffron-lion.sh
        container: qc.doc_nerdy-ochre-mammoth
      github.com/dCache/dcache git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-scarlet-cuscus.sh
        container: qc.doc_frumpy-cobalt-chin
      github.com/dCache/dcache markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-fuchsia-hippopotamus.sh
        container: qc.doc_crappy-khaki-bandicoot
  QC.Lic:
    repos:
      github.com/dCache/dcache licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-amaranth-macaque.sh
        container: qc.lic_lanky-saffron-jackal
  QC.Met:
    repos:
      github.com/dCache/dcache cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-sangria-sparrow.sh
        container: qc.met_freaky-salmon-walrus
  QC.Sec:
    repos:
      github.com/dCache/dcache bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-orange-capuchin.sh
        container: qc.sec_lanky-crimson-kakapo
  QC.Sty:
    repos:
      github.com/dCache/dcache checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.randy-linen-owl.sh
        container: qc.sty_greasy-ecru-bracke
      github.com/dCache/dcache flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gamboge-grouse.sh
        container: qc.sty_gimpy-maroon-pinscher
      github.com/dCache/dcache hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cardinal-capuchin.sh
        container: qc.sty_bumpy-sapphire-crane
      github.com/dCache/dcache jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-olive-cow.sh
        container: qc.sty_grumpy-alizarin-schnauzer
      github.com/dCache/dcache rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cinnamon-dormouse.sh
        container: qc.sty_dorky-denim-schnauzer
  QC.Ver:
    repos:
      github.com/dCache/dcache get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-white-dhole.sh
        container: qc.ver_shaky-white-scorpion
timeout: 5400
